"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-14 23:12:14.508614

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("title_en", sa.String(length=255), nullable=True),
        sa.Column("title_ja", sa.String(length=255), nullable=True),
        sa.Column("title_zh", sa.String(length=255), nullable=True),
        sa.Column("system", sa.String(length=32), nullable=False),
        sa.Column("cover_key", sa.String(length=512), nullable=True),
        sa.Column("developer", sa.String(length=255), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_games_system"), ["system"], unique=False)
        batch_op.create_index(batch_op.f("ix_games_title"), ["title"], unique=False)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "game_emulator_configs",
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("emulator_id", sa.String(length=64), nullable=False),
        sa.Column("core", sa.String(length=64), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "user_id", "emulator_id", name="uq_game_emulator_config"),
    )
    with op.batch_alter_table("game_emulator_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_game_emulator_configs_game_id"), ["game_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_emulator_configs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "game_files",
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("extension", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("missing", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_game_files_sha256"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("game_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_files_game_id"), ["game_id"], unique=False)

    op.create_table(
        "game_saves",
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("save_type", sa.String(length=16), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("screenshot_key", sa.String(length=1024), nullable=True),
        sa.Column("emulator_id", sa.String(length=64), nullable=False),
        sa.Column("core_id", sa.String(length=64), nullable=True),
        sa.Column("core_version", sa.String(length=64), nullable=True),
        sa.Column("client_modified_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "user_id", "save_type", "slot", name="uq_game_saves_slot"),
    )
    with op.batch_alter_table("game_saves", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_saves_game_id"), ["game_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_game_saves_user_id"), ["user_id"], unique=False)

    op.create_table(
        "play_sessions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("device", sa.String(length=255), nullable=True),
        sa.Column("emulator_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("play_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_play_sessions_ended_at"), ["ended_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_sessions_game_id"), ["game_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("play_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_play_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_play_sessions_game_id"))
        batch_op.drop_index(batch_op.f("ix_play_sessions_ended_at"))

    op.drop_table("play_sessions")
    with op.batch_alter_table("game_saves", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_saves_user_id"))
        batch_op.drop_index(batch_op.f("ix_game_saves_game_id"))

    op.drop_table("game_saves")
    with op.batch_alter_table("game_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_files_game_id"))

    op.drop_table("game_files")
    with op.batch_alter_table("game_emulator_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_emulator_configs_user_id"))
        batch_op.drop_index(batch_op.f("ix_game_emulator_configs_game_id"))

    op.drop_table("game_emulator_configs")
    op.drop_table("users")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_title"))
        batch_op.drop_index(batch_op.f("ix_games_system"))

    op.drop_table("games")
    # ### end Alembic commands ###
